<a href="https://colab.research.google.com/github/madelineekim/pytorch-basics/blob/main/00_pytorch_fudamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu124


Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Random Tensors

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9175, 0.3589, 0.1742, 0.6258],
        [0.4739, 0.2182, 0.3363, 0.2190],
        [0.0698, 0.0488, 0.9741, 0.4739]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeroes and Ones

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes! (common point of error in Pytorch and deep learning)

The three common errors:
1. Tensors are wrong type
2. Tensors are wrong shape
3. Tensors not on right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, #datatype
                               device=None, #what device
                               requires_grad=False) #does it track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8731, 0.3015, 0.0404, 0.2683],
        [0.5263, 0.6901, 0.4543, 0.6656],
        [0.3178, 0.6523, 0.0876, 0.0736]])

In [ ]:
print(some_tensor)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.8731, 0.3015, 0.0404, 0.2683],
        [0.5263, 0.6901, 0.4543, 0.6656],
        [0.3178, 0.6523, 0.0876, 0.0736]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


Tensor operations include:
Addition, Subtraction, Multiplication, Division, Matrix multiplication

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

Matrix Multiplication

The inner dimensions must match (cols of first and rows of second)
The resulting matrix has the shape of the outer dimensions

In [ ]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
new_tensor = torch.rand(3, 4)
new_tensor2 = torch.rand(4, 3)
torch.mm(new_tensor, new_tensor2)

tensor([[2.2238, 1.9533, 2.1127],
        [1.6799, 1.1907, 1.8809],
        [2.2731, 1.8479, 2.3582]])

To fix tensor shapes, we can manipulate the shape of one of them using a transpose.

A transpose switches the axes of a given tensor

In [ ]:
tensor_wrong = torch.rand(3,4)
tensor_wrong

tensor([[0.5144, 0.5430, 0.9576, 0.4490],
        [0.5912, 0.3983, 0.6535, 0.3164],
        [0.0448, 0.6838, 0.8653, 0.1934]])

In [ ]:
tensor_wrong.T

tensor([[0.5144, 0.5912, 0.0448],
        [0.5430, 0.3983, 0.6838],
        [0.9576, 0.6535, 0.8653],
        [0.4490, 0.3164, 0.1934]])

In [ ]:
torch.mm(tensor_wrong.T, new_tensor)

tensor([[0.5955, 1.0626, 0.4958, 0.8379],
        [0.6970, 1.3446, 1.0842, 1.3438],
        [1.0373, 2.1005, 1.6028, 2.0149],
        [0.4038, 0.8522, 0.5609, 0.7495]])

Tensor aggregation

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Finding positional min max

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

Reshaping, stacking, squeezing, and unsqueezing tensors
* Reshaping - reshapes an input tensor
* View - return a view of an input tensor without modifying it
* Stacking - combine multiple tensors on top (vstack) or side by side (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a way

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape((9, 1))
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
x_reshaped.shape

torch.Size([9, 1])

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
torch.permute(x_reshaped, (0, 1))

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
x_picture = torch.rand(size=(224, 224, 3))
x_picture

tensor([[[0.7310, 0.3933, 0.4060],
         [0.9445, 0.5929, 0.7140],
         [0.4513, 0.0085, 0.7446],
         ...,
         [0.8503, 0.6518, 0.7272],
         [0.2163, 0.0150, 0.4963],
         [0.1832, 0.4742, 0.7256]],

        [[0.9371, 0.8266, 0.3173],
         [0.6624, 0.5888, 0.4558],
         [0.7446, 0.1424, 0.4281],
         ...,
         [0.8143, 0.3738, 0.4516],
         [0.7879, 0.3231, 0.9530],
         [0.4759, 0.9793, 0.4647]],

        [[0.0506, 0.6990, 0.6266],
         [0.6982, 0.9570, 0.3329],
         [0.8172, 0.9221, 0.1327],
         ...,
         [0.1861, 0.1121, 0.9572],
         [0.0993, 0.3994, 0.8652],
         [0.4003, 0.4344, 0.0240]],

        ...,

        [[0.3451, 0.3407, 0.0827],
         [0.4651, 0.7048, 0.0165],
         [0.9113, 0.3700, 0.4169],
         ...,
         [0.3272, 0.4366, 0.7566],
         [0.4150, 0.2942, 0.0574],
         [0.0941, 0.1679, 0.3886]],

        [[0.5309, 0.8745, 0.4964],
         [0.5055, 0.9513, 0.1389],
         [0.

In [ ]:
torch.permute(x_picture, (2, 0, 1))

tensor([[[0.7310, 0.9445, 0.4513,  ..., 0.8503, 0.2163, 0.1832],
         [0.9371, 0.6624, 0.7446,  ..., 0.8143, 0.7879, 0.4759],
         [0.0506, 0.6982, 0.8172,  ..., 0.1861, 0.0993, 0.4003],
         ...,
         [0.3451, 0.4651, 0.9113,  ..., 0.3272, 0.4150, 0.0941],
         [0.5309, 0.5055, 0.2319,  ..., 0.1531, 0.8082, 0.2763],
         [0.7021, 0.8557, 0.9632,  ..., 0.0714, 0.1450, 0.0844]],

        [[0.3933, 0.5929, 0.0085,  ..., 0.6518, 0.0150, 0.4742],
         [0.8266, 0.5888, 0.1424,  ..., 0.3738, 0.3231, 0.9793],
         [0.6990, 0.9570, 0.9221,  ..., 0.1121, 0.3994, 0.4344],
         ...,
         [0.3407, 0.7048, 0.3700,  ..., 0.4366, 0.2942, 0.1679],
         [0.8745, 0.9513, 0.2826,  ..., 0.4695, 0.7501, 0.2643],
         [0.4327, 0.9337, 0.9054,  ..., 0.1495, 0.4182, 0.4478]],

        [[0.4060, 0.7140, 0.7446,  ..., 0.7272, 0.4963, 0.7256],
         [0.3173, 0.4558, 0.4281,  ..., 0.4516, 0.9530, 0.4647],
         [0.6266, 0.3329, 0.1327,  ..., 0.9572, 0.8652, 0.

Indexing (similar to NumPy)

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0, 0]

tensor([1, 2, 3])

In [ ]:
x[0, 0, 0]

tensor(1)

In [ ]:
x[0, 2, 2]

tensor(9)

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

PyTorch and NumPy:
* torch.from_numpy(ndarray)
* torch.Tensor.numpy()

---



In [ ]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting from numpy to pytorch pytorch reflects numpy datatype which is float 64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
array = array + 1
array, tensor # tensor doesn't change

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducibility:
* in short how a neural network learns: start w/ random numbers -> tensor operations -> update random numbers to try to make better representation of data -> repeat
* to reduce randomness we need random seeds



In [ ]:
import torch
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3479, 0.2256, 0.5268, 0.3819],
        [0.1843, 0.9670, 0.5238, 0.1618],
        [0.2710, 0.0501, 0.9826, 0.2669]])
tensor([[0.7376, 0.8406, 0.4714, 0.8382],
        [0.8765, 0.0554, 0.1683, 0.4691],
        [0.9205, 0.3197, 0.7092, 0.4026]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C == random_tensor_D)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Running tensors on GPUs

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
torch.cuda.is_available()

False

Setup device agnostic code

In [ ]:
device= "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
torch.cuda.device_count()

0

How to put tensors on a GPU

In [ ]:
tensor = torch.tensor([1, 2, 3], device="cpu")
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

Tensors on GPU can't be transformed to NumPy

In [ ]:
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])